### ISSUE TITLE
Hint about Hash Join Node

### ISSUE THREAD

**Issue by lrweck** [hairybreeches/pgMustard#15]
Hey !

Both are the exact same query, but the second one has much more work_mem set. In the first one (https://pastebin.com/anyGD9FV), node #24 pgMustard tells me to restructure the query, but it doesn't in the second plan (https://pastebin.com/P85yRbc2). I guess work_mem affects the speed of Hash Joins aswell, maybe that's the reason?

**Comment by hairybreeches** [comment]
Hi! Thanks for filing this issue!

I think the reason you're seeing different tips is less to do with the has join itself, and more to do with the sequential scan that is its first child.

In the first example, the sequential scan takes 7.8s, while in the second case it only takes 2.6s - probably at least partly due to a slightly higher cache hit % (30% vs 42% in postgres itself, and maybe a little bit more at the OS level).

This means that, since there will be less time saved by speeding up that sequential scan, the advice to read fewer rows is less useful, and so fails to make the cutoff as a tip that will significantly improve your overall query performance (remember total query time is 40s and 25s respectively).

Hope this helps!

**Comment by hairybreeches** [comment]
Hi Luis -

I'm closing this issue now, let me know if there's anything more we can help with on this one.
