### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by lrweck** [hairybreeches/pgMustard#17]
Hey!

More nitpicking! :sweat_smile:

Rounding to 1.0, especially on large numbers, makes it look like "out by a factor of X" is relevant.

Maybe when it's close to 1% difference it can tell that statistics are accurate for the expected execution.

![image](https://user-images.githubusercontent.com/26086198/66044075-20365f00-e4f7-11e9-92e5-830f433d8afe.png)

**Comment by mchristofides** [comment]
Thank you! Not nit-picking at all, we'll improve the wording here. Since it will round to 1.0 for anything within 5%, we'll probably use that as the threshold!

**Comment by hairybreeches** [comment]
Agreed, this is not nitpicking at all - very useful feedback. I'll get on it after finishing #18

**Comment by hairybreeches** [comment]
I've updated this to say "accurate to within 5%" instead of "out by a factor of 1.0". You can check it out on node #2 on example 1:

![2019-10-15_14-24-02](https://user-images.githubusercontent.com/709166/66835611-bf2b7400-ef57-11e9-8244-7f96c4838102.png)

This fix was added in commit 335370da82c65a60f4c7defa6f2df3ecf644b7a2, deployed at 14:31 15/10/2019
